# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # make vm jenkins
  config.vm.define "jenkins" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "jenkins"
    node.vm.network "private_network", ip: "172.16.10.105"
    node.vm.provision "shell", path: "setup.sh"   
  end                  
                  
end